### ISSUE TITLE
new future

### ISSUE THREAD

**Issue by ovulatingwife** [thevindu-w/clip_share_client#3]
在传输中文时会乱码，另外分享时必须转到应用前台点击发送后才能传输，可不可以点击分享直接在后台发送，另外希望可以复制文本后，点击通知栏里的快捷按钮发送剪切板中的内容，以及在分享链接时可以直接在浏览器中打开，最最最重要的是希望可以双向传输。
类似的功能可以在[KDE Connect](https://kdeconnect.kde.org/)、Pasteasy、[MFiles](https://mfiles.maokebing.com/)、[Fnsync](https://gitee.com/holmium/fnsync)查看

**Comment by thevindu-w** [comment]
**Note**: I use Google Translate to read the message in English. If there is anything incorrectly interpreted, please correct me.
Also, if possible, let's continue the conversation in English.
<br>

> When transmitting Chinese, the characters will be garbled.

- Can you please give a sample Chinese text that is not correctly transmitted? Does all Chinese text get changed, or is it only some specific text/characters?
- Does this happen when sending Chinese text from phone to laptop, or when getting from laptop to phone, or both directions?
<br>

> Can you click Share to send directly in the background?

I am also planning to do that. But, I am worried about the restrictions on accessing the clipboard in the background. There are many restrictions in newer Android versions. But anyway, I will try to implement that as it is a useful feature.
<br>

> I hope that after copying the text, click the shortcut button in the notification bar to send it in the clipboard.

I think you meant by this is, "When we copy some text in the mobile, a notification with a send button appears. When we click the send button in the notification, it will send the text to laptop". Yes, that would be useful. But I think it also has to read the clipboard in the background. If I can get the background sync working, I can try this as well.
<br>

> The content can be opened directly in the browser when sharing the link.

What I understood from this is, "The mobile app should detect if the text it received from the laptop is a link. If so, it should give the option to directly open the link in the browser". If this is what you meant, I will try to implement that.
<br>

> The most important thing is that it can be transmitted in both directions.

I didn't clearly understand what this exactly meant (possibly due to translation errors). Can you please explain more? I guess you are not asking about sending text from mobile to laptop and getting text from laptop to mobile as the app already supports sending text in both directions.

**Comment by thevindu-w** [comment]
The bug where Chinese characters (and other non-ASCII characters) not correctly transferring is now fixed. In fact, the bug was in the Windows version of the server. You can get the latest version from [https://github.com/thevindu-w/clip_share_server/releases](https://github.com/thevindu-w/clip_share_server/releases). If the bug is still there in the new release, please re-open this issue.
